# -------- sweep_arch_phase.yaml --------
program: sweep_arch.py
method: grid 
metric: {name: val_loss, goal: minimize}
early_terminate: {type: hyperband, min_iter: 2}

parameters:
  cfg_template: {value: configs/phase2_base.yaml}

  # ─ Architecture search ─
  num_channels:   {values: [1, 3, 6, 12]}
  dilation_depth: {values: [8, 9 , 10]}
  num_repeat:     {values: [1, 2, 3, 4]}
  kernel_size:    {values: [5, 7, 9]}

  # ─ Fixed HPs (phase-1 best) ─
  batch_size:    {value: 128}
  learning_rate: {value: 5e-3}

project: ongsanet-training
entity:  test_12342
